esphome:
  name: balcony
  platform: ESP8266
  board: esp12e
  esp8266_restore_from_flash: yes

wifi:
  ssid: !secret wifi-east
  password: !secret wifi-pwd

  use_address: esp-balcony.ak-online.be

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Balcony Fallback Hotspot"
    password: !secret fallback-password

mdns:
  disabled: true

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
#api:

mqtt:
  broker: mqtt.ak-online.be
  discovery: true
  topic_prefix: esphome/balcony

ota:

web_server:
  port: 80

i2c:
  sda: GPIO4
  scl: GPIO5
  scan: True

sensor:
  - platform: wifi_signal
    name: "WiFi Signal ESP Balcony"
    update_interval: 60s
  - platform: bme280
    temperature:
      name: "Balcony Temperature"
      oversampling: 16x
    pressure:
      name: "Balcony Pressure"
    humidity:
      name: "Balcony Humidity"
    address: 0x76
    update_interval: 30s
  - platform: bh1750
    name: "Balcony Illuminance"
    address: 0x23
      #measurement_time: 69
    update_interval: 30s
