esphome:
  name: dmx01
  platform: ESP32
  board: nodemcu-32s
  #platformio_options:
  #upload_speed: 115200

wifi:
  ssid: !secret wifi-east
  password: !secret wifi-pwd

  use_address: esp-dmx01.ak-online.be

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "dmx01 Fallback Hotspot"
    password: !secret fallback-password


mdns:
  disabled: true

logger:
  baud_rate: 0
# logs:
#   dmx512: INFO

# Enable Home Assistant API
#api:

mqtt:
  broker: mqtt.ak-online.be
  discovery: true
  topic_prefix: esphome/dmx01

ota:

web_server:
  port: 80
  include_internal: true

wled:

external_components:
  - source: github://andyboeh/esphome-dmx512

uart:
  id: uart_bus
  baud_rate: 250000
  tx_pin: 32
  stop_bits: 2
#  debug:
#    direction: TX
#    dummy_receiver: false
#    after:
#      timeout: 100ms
#    sequence:
#      - lambda: UARTDebug::log_hex(direction, bytes, ' ');

dmx512:
  id: dmx
  uart_id: uart_bus
  enable_pin: 33
  tx_pin: 32
  uart_num: 1

output:
  - platform: gpio
    pin: GPIO02
    id: out_led

  - platform: dmx512
    universe: dmx
    channel: 1
    id: dmx_ch001
  - platform: dmx512
    universe: dmx
    channel: 2
    id: dmx_ch002
  - platform: dmx512
    universe: dmx
    channel: 3
    id: dmx_ch003
  - platform: dmx512
    universe: dmx
    channel: 4
    id: dmx_ch004
  - platform: dmx512
    universe: dmx
    channel: 5
    id: dmx_ch005
  - platform: dmx512
    universe: dmx
    channel: 6
    id: dmx_ch006
  - platform: dmx512
    universe: dmx
    channel: 7
    id: dmx_ch007
  - platform: dmx512
    universe: dmx
    channel: 8
    id: dmx_ch008
  - platform: dmx512
    universe: dmx
    channel: 9
    id: dmx_ch009

  - platform: dmx512
    universe: dmx
    channel: 10
    id: dmx_ch010
  - platform: dmx512
    universe: dmx
    channel: 11
    id: dmx_ch011
  - platform: dmx512
    universe: dmx
    channel: 12
    id: dmx_ch012

  - platform: dmx512
    universe: dmx
    channel: 13
    id: dmx_ch013
  - platform: dmx512
    universe: dmx
    channel: 14
    id: dmx_ch014
  - platform: dmx512
    universe: dmx
    channel: 15
    id: dmx_ch015

  - platform: dmx512
    universe: dmx
    channel: 16
    id: dmx_ch016
  - platform: dmx512
    universe: dmx
    channel: 17
    id: dmx_ch017
  - platform: dmx512
    universe: dmx
    channel: 18
    id: dmx_ch018

  - platform: dmx512
    universe: dmx
    channel: 19
    id: dmx_ch019
  - platform: dmx512
    universe: dmx
    channel: 20
    id: dmx_ch020
  - platform: dmx512
    universe: dmx
    channel: 21
    id: dmx_ch021

  - platform: dmx512
    universe: dmx
    channel: 22
    id: dmx_ch022
  - platform: dmx512
    universe: dmx
    channel: 23
    id: dmx_ch023
  - platform: dmx512
    universe: dmx
    channel: 24
    id: dmx_ch024

light:
  - platform: binary
    id: status
    output: out_led

number:
    - platform: template
      name: "Ch 001 value"
      optimistic: true
      internal: true
      min_value: 0
      max_value: 255
      step: 1
      set_action:
        - output.set_level:
            id: dmx_ch001
            level: !lambda return x/255.0;

    - platform: template
      name: "Ch 002 value"
      optimistic: true
      internal: true
      min_value: 0
      max_value: 255
      step: 1
      set_action:
        - output.set_level:
            id: dmx_ch002
            level: !lambda return x/255.0;

    - platform: template
      name: "Ch 003 value"
      optimistic: true
      internal: true
      min_value: 0
      max_value: 255
      step: 1
      set_action:
        - output.set_level:
            id: dmx_ch003
            level: !lambda return x/255.0;

    - platform: template
      name: "Ch 004 value"
      optimistic: true
      internal: true
      min_value: 0
      max_value: 255
      step: 1
      set_action:
        - output.set_level:
            id: dmx_ch004
            level: !lambda return x/255.0;

    - platform: template
      name: "Ch 005 value"
      optimistic: true
      internal: true
      min_value: 0
      max_value: 255
      step: 1
      set_action:
        - output.set_level:
            id: dmx_ch005
            level: !lambda return x/255.0;

    - platform: template
      name: "Ch 006 value"
      optimistic: true
      internal: true
      min_value: 0
      max_value: 255
      step: 1
      set_action:
        - output.set_level:
            id: dmx_ch006
            level: !lambda return x/255.0;

    - platform: template
      name: "Ch 007 value"
      optimistic: true
      internal: true
      min_value: 0
      max_value: 255
      step: 1
      set_action:
        - output.set_level:
            id: dmx_ch007
            level: !lambda return x/255.0;

    - platform: template
      name: "Ch 008 value"
      optimistic: true
      internal: true
      min_value: 0
      max_value: 255
      step: 1
      set_action:
        - output.set_level:
            id: dmx_ch008
            level: !lambda return x/255.0;

    - platform: template
      name: "Ch 009 value"
      optimistic: true
      internal: true
      min_value: 0
      max_value: 255
      step: 1
      set_action:
        - output.set_level:
            id: dmx_ch009
            level: !lambda return x/255.0;

    - platform: template
      name: "Ch 010 value"
      optimistic: true
      internal: true
      min_value: 0
      max_value: 255
      step: 1
      set_action:
        - output.set_level:
            id: dmx_ch010
            level: !lambda return x/255.0;

    - platform: template
      name: "Ch 011 value"
      optimistic: true
      internal: true
      min_value: 0
      max_value: 255
      step: 1
      set_action:
        - output.set_level:
            id: dmx_ch011
            level: !lambda return x/255.0;

    - platform: template
      name: "Ch 012 value"
      optimistic: true
      internal: true
      min_value: 0
      max_value: 255
      step: 1
      set_action:
        - output.set_level:
            id: dmx_ch012
            level: !lambda return x/255.0;
