esphome:
  name: dmx
  platform: ESP32
  board: nodemcu-32s
  #platformio_options:
  #upload_speed: 115200

#wifi:
#  ssid: !secret wifi-east
#  password: !secret wifi-pwd
#
#  use_address: rgb_mainframe.ak-online.be
#
#  # Enable fallback hotspot (captive portal) in case wifi connection fails
#  ap:
#    ssid: "RGB Mainframe Fallback Hotspot"
#    password: !secret fallback-password


ethernet:
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO0_IN
  phy_addr: 1
  power_pin: GPIO16
  use_address: esp-dmx.ak-online.be
#  manual_ip:
#    static_ip: 172.16.2.50
#    gateway: 172.16.0.1
#    subnet: 255.255.252.0
#    dns1: 172.16.0.1
#    dns2: 172.16.0.253

    #captive_portal:
mdns:
  disabled: true

# Enable logging
logger:
  # important: disable serial logging, UARTs are taken by eth nic
  baud_rate: 0

# Enable Home Assistant API
#api:

mqtt:
  broker: mqtt.ak-online.be
  discovery: true
  topic_prefix: esphome/dmx

ota:

web_server:
  port: 80

wled:

external_components:
  - source: github://andyboeh/esphome-dmx512

uart:
  id: uart_bus
  baud_rate: 250000
  tx_pin: 32
  stop_bits: 2

dmx512:
  id: dmx
  uart_id: uart_bus
  enable_pin: 33
  tx_pin: 32
  uart_num: 1

output:
  - platform: gpio
    pin: GPIO02
    id: out_led

  - platform: dmx512
    universe: dmx
    channel: 1
    id: dmx_ch1_brightness
  - platform: dmx512
    universe: dmx
    channel: 2
    id: dmx_ch1_red
  - platform: dmx512
    universe: dmx
    channel: 3
    id: dmx_ch1_green
  - platform: dmx512
    universe: dmx
    channel: 4
    id: dmx_ch1_blue

  - platform: dmx512
    universe: dmx
    channel: 8
    id: dmx_ch2_brightness
  - platform: dmx512
    universe: dmx
    channel: 9
    id: dmx_ch2_red
  - platform: dmx512
    universe: dmx
    channel: 10
    id: dmx_ch2_green
  - platform: dmx512
    universe: dmx
    channel: 11
    id: dmx_ch2_blue

  - platform: dmx512
    universe: dmx
    channel: 15
    id: dmx_ch3_brightness
  - platform: dmx512
    universe: dmx
    channel: 16
    id: dmx_ch3_red
  - platform: dmx512
    universe: dmx
    channel: 17
    id: dmx_ch3_green
  - platform: dmx512
    universe: dmx
    channel: 18
    id: dmx_ch3_blue

  - platform: dmx512
    universe: dmx
    channel: 27
    id: dmx_ch4_brightness
  - platform: dmx512
    universe: dmx
    channel: 28
    id: dmx_ch4_red
  - platform: dmx512
    universe: dmx
    channel: 29
    id: dmx_ch4_green
  - platform: dmx512
    universe: dmx
    channel: 30
    id: dmx_ch4_blue

light:
  - platform: rgb
    name: "DMX Light addr1"
    id: dmx_light_addr1
    gamma_correct: 1.0
    red: dmx_ch1_red
    green: dmx_ch1_green
    blue: dmx_ch1_blue
    on_turn_on:
      - output.set_level:
          id: dmx_ch1_brightness
          level: 100%
    on_turn_off:
      - output.set_level:
          id: dmx_ch1_brightness
          level: 0%

  - platform: rgb
    name: "DMX Light addr8"
    id: dmx_light_addr8
    gamma_correct: 1.0
    red: dmx_ch2_red
    green: dmx_ch2_green
    blue: dmx_ch2_blue
    on_turn_on:
      - output.set_level:
          id: dmx_ch2_brightness
          level: 100%
    on_turn_off:
      - output.set_level:
          id: dmx_ch2_brightness
          level: 0%

  - platform: rgb
    name: "DMX Light addr15"
    id: dmx_light_addr15
    gamma_correct: 1.0
    red: dmx_ch3_red
    green: dmx_ch3_green
    blue: dmx_ch3_blue
    on_turn_on:
      - output.set_level:
          id: dmx_ch3_brightness
          level: 100%
    on_turn_off:
      - output.set_level:
          id: dmx_ch3_brightness
          level: 0%

  - platform: rgb
    name: "DMX Light addr27"
    id: dmx_light_addr27
    gamma_correct: 1.0
    red: dmx_ch4_red
    green: dmx_ch4_green
    blue: dmx_ch4_blue
    on_turn_on:
      - output.set_level:
          id: dmx_ch4_brightness
          level: 100%
    on_turn_off:
      - output.set_level:
          id: dmx_ch4_brightness
          level: 0%

  - platform: partition
    name: "DMX Growlights"
    gamma_correct: 1.0
    segments:
      - single_light_id: dmx_light_addr1
      - single_light_id: dmx_light_addr8
      - single_light_id: dmx_light_addr15
      - single_light_id: dmx_light_addr27
    effects:
      - addressable_rainbow:
      - addressable_color_wipe:
      - addressable_scan:
      - addressable_twinkle:
      - !include effects/ColorShimmerEffect.yaml
    on_turn_on:
      - output.set_level:
          id: dmx_ch1_brightness
          level: 100%
      - output.set_level:
          id: dmx_ch2_brightness
          level: 100%
      - output.set_level:
          id: dmx_ch3_brightness
          level: 100%
      - output.set_level:
          id: dmx_ch4_brightness
          level: 100%
    on_turn_off:
      - output.set_level:
          id: dmx_ch1_brightness
          level: 0%
      - output.set_level:
          id: dmx_ch2_brightness
          level: 0%
      - output.set_level:
          id: dmx_ch3_brightness
          level: 0%
      - output.set_level:
          id: dmx_ch4_brightness
          level: 0%


  - platform: binary
    id: status
    output: out_led

