esphome:
  name: eth_dmx
  platform: ESP32
  board: nodemcu-32s
  #platformio_options:
  #upload_speed: 115200

  includes:
    - audio-reactive-led-strip/audio-reactive-led-strip
    - audio-reactive-led-strip/esphome-music-leds

  on_boot:
    priority: 100
    then:
      - output.set_level:
          id: dmx_ch1_brightness
          level: 100%
      - output.set_level:
          id: dmx_ch2_brightness
          level: 100%
      - output.set_level:
          id: dmx_ch3_brightness
          level: 100%
      - output.set_level:
          id: dmx_ch4_brightness
          level: 100%
      - output.set_level:
          id: dmx_ch1_mode
          level: 0%
      - output.set_level:
          id: dmx_ch2_mode
          level: 0%
      - output.set_level:
          id: dmx_ch3_mode
          level: 0%
      - output.set_level:
          id: dmx_ch4_mode
          level: 0%

#wifi:
#  ssid: !secret wifi-east
#  password: !secret wifi-pwd
#
#  use_address: rgb_mainframe.ak-online.be
#
#  # Enable fallback hotspot (captive portal) in case wifi connection fails
#  ap:
#    ssid: "RGB Mainframe Fallback Hotspot"
#    password: !secret fallback-password


ethernet:
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO0_IN
  phy_addr: 1
  power_pin: GPIO16
  use_address: esp-dmx.ak-online.be
#  manual_ip:
#    static_ip: 172.16.2.50
#    gateway: 172.16.0.1
#    subnet: 255.255.252.0
#    dns1: 172.16.0.1
#    dns2: 172.16.0.253

    #captive_portal:
mdns:
  disabled: true

# Enable logging
logger:
  # important: disable serial logging, UARTs are taken by eth nic
  baud_rate: 0
  logs:
    dmx512: INFO
    MusicLeds: INFO

# Enable Home Assistant API
#api:

mqtt:
  broker: mqtt.ak-online.be
  discovery: true
  topic_prefix: esphome/dmx

ota:

web_server:
  port: 80
  include_internal: true

button:
  - platform: restart
    name: restart

wled:

external_components:
  - source: github://andyboeh/esphome-dmx512

uart:
  id: uart_bus
  baud_rate: 250000
  tx_pin: 17
  stop_bits: 2

dmx512:
  id: dmx
  uart_id: uart_bus
  enable_pin: 5
  tx_pin: 17
  uart_num: 1

output:
  - platform: gpio
    pin: GPIO02
    id: out_led

  - platform: dmx512
    universe: dmx
    channel: 1
    id: dmxbar_ch1_red
  - platform: dmx512
    universe: dmx
    channel: 2
    id: dmxbar_ch1_green
  - platform: dmx512
    universe: dmx
    channel: 3
    id: dmxbar_ch1_blue

  - platform: dmx512
    universe: dmx
    channel: 4
    id: dmxbar_ch2_red
  - platform: dmx512
    universe: dmx
    channel: 5
    id: dmxbar_ch2_green
  - platform: dmx512
    universe: dmx
    channel: 6
    id: dmxbar_ch2_blue

  - platform: dmx512
    universe: dmx
    channel: 7
    id: dmxbar_ch3_red
  - platform: dmx512
    universe: dmx
    channel: 8
    id: dmxbar_ch3_green
  - platform: dmx512
    universe: dmx
    channel: 9
    id: dmxbar_ch3_blue

  - platform: dmx512
    universe: dmx
    channel: 10
    id: dmxbar_ch4_red
  - platform: dmx512
    universe: dmx
    channel: 11
    id: dmxbar_ch4_green
  - platform: dmx512
    universe: dmx
    channel: 12
    id: dmxbar_ch4_blue

  - platform: dmx512
    universe: dmx
    channel: 13
    id: dmxbar_ch5_red
  - platform: dmx512
    universe: dmx
    channel: 14
    id: dmxbar_ch5_green
  - platform: dmx512
    universe: dmx
    channel: 15
    id: dmxbar_ch5_blue

  - platform: dmx512
    universe: dmx
    channel: 16
    id: dmxbar_ch6_red
  - platform: dmx512
    universe: dmx
    channel: 17
    id: dmxbar_ch6_green
  - platform: dmx512
    universe: dmx
    channel: 18
    id: dmxbar_ch6_blue

  - platform: dmx512
    universe: dmx
    channel: 19
    id: dmxbar_ch7_red
  - platform: dmx512
    universe: dmx
    channel: 20
    id: dmxbar_ch7_green
  - platform: dmx512
    universe: dmx
    channel: 21
    id: dmxbar_ch7_blue

  - platform: dmx512
    universe: dmx
    channel: 22
    id: dmxbar_ch8_red
  - platform: dmx512
    universe: dmx
    channel: 23
    id: dmxbar_ch8_green
  - platform: dmx512
    universe: dmx
    channel: 24
    id: dmxbar_ch8_blue

  - platform: dmx512
    universe: dmx
    channel: 25
    id: dmx_ch1_brightness
  - platform: dmx512
    universe: dmx
    channel: 26
    id: dmx_ch1_red
  - platform: dmx512
    universe: dmx
    channel: 27
    id: dmx_ch1_green
  - platform: dmx512
    universe: dmx
    channel: 28
    id: dmx_ch1_blue
  - platform: dmx512
    universe: dmx
    channel: 30
    id: dmx_ch1_mode

  - platform: dmx512
    universe: dmx
    channel: 32
    id: dmx_ch2_brightness
  - platform: dmx512
    universe: dmx
    channel: 33
    id: dmx_ch2_red
  - platform: dmx512
    universe: dmx
    channel: 34
    id: dmx_ch2_green
  - platform: dmx512
    universe: dmx
    channel: 35
    id: dmx_ch2_blue
  - platform: dmx512
    universe: dmx
    channel: 37
    id: dmx_ch2_mode

  - platform: dmx512
    universe: dmx
    channel: 39
    id: dmx_ch3_brightness
  - platform: dmx512
    universe: dmx
    channel: 40
    id: dmx_ch3_red
  - platform: dmx512
    universe: dmx
    channel: 41
    id: dmx_ch3_green
  - platform: dmx512
    universe: dmx
    channel: 42
    id: dmx_ch3_blue
  - platform: dmx512
    universe: dmx
    channel: 44
    id: dmx_ch3_mode

  - platform: dmx512
    universe: dmx
    channel: 46
    id: dmx_ch4_brightness
  - platform: dmx512
    universe: dmx
    channel: 47
    id: dmx_ch4_red
  - platform: dmx512
    universe: dmx
    channel: 48
    id: dmx_ch4_green
  - platform: dmx512
    universe: dmx
    channel: 49
    id: dmx_ch4_blue
  - platform: dmx512
    universe: dmx
    channel: 51
    id: dmx_ch4_mode

light:
  - platform: rgb
    name: "Growlight 01 - Bar 1"
    internal: true
    id: dmxbar_bar_1
    gamma_correct: 1.0
    default_transition_length: 0s
    red: dmxbar_ch1_red
    green: dmxbar_ch1_green
    blue: dmxbar_ch1_blue

  - platform: rgb
    name: "Growlight 02 - Bar 2"
    internal: true
    id: dmxbar_bar_2
    gamma_correct: 1.0
    default_transition_length: 0s
    red: dmxbar_ch2_red
    green: dmxbar_ch2_green
    blue: dmxbar_ch2_blue

  - platform: rgb
    name: "Growlight 03 - Bar 3"
    internal: true
    id: dmxbar_bar_3
    gamma_correct: 1.0
    default_transition_length: 0s
    red: dmxbar_ch3_red
    green: dmxbar_ch3_green
    blue: dmxbar_ch3_blue

  - platform: rgb
    name: "Growlight 04 - Bar 4"
    internal: true
    id: dmxbar_bar_4
    gamma_correct: 1.0
    default_transition_length: 0s
    red: dmxbar_ch4_red
    green: dmxbar_ch4_green
    blue: dmxbar_ch4_blue

  - platform: rgb
    name: "Growlight 05 - Bar 5"
    internal: true
    id: dmxbar_bar_5
    gamma_correct: 1.0
    default_transition_length: 0s
    red: dmxbar_ch5_red
    green: dmxbar_ch5_green
    blue: dmxbar_ch5_blue

  - platform: rgb
    name: "Growlight 06 - Bar 6"
    internal: true
    id: dmxbar_bar_6
    gamma_correct: 1.0
    default_transition_length: 0s
    red: dmxbar_ch6_red
    green: dmxbar_ch6_green
    blue: dmxbar_ch6_blue

  - platform: rgb
    name: "Growlight 07 - Bar 7"
    internal: true
    id: dmxbar_bar_7
    gamma_correct: 1.0
    default_transition_length: 0s
    red: dmxbar_ch7_red
    green: dmxbar_ch7_green
    blue: dmxbar_ch7_blue

  - platform: rgb
    name: "Growlight 08 - Bar 8"
    internal: true
    id: dmxbar_bar_8
    gamma_correct: 1.0
    default_transition_length: 0s
    red: dmxbar_ch8_red
    green: dmxbar_ch8_green
    blue: dmxbar_ch8_blue

  - platform: rgb
    name: "Growlight 09 - Light 25"
    internal: true
    id: dmx_light_addr1
    gamma_correct: 1.0
    default_transition_length: 0s
    red: dmx_ch1_red
    green: dmx_ch1_green
    blue: dmx_ch1_blue

  - platform: rgb
    name: "Growlight 10 - Light 32"
    internal: true
    id: dmx_light_addr8
    gamma_correct: 1.0
    default_transition_length: 0s
    red: dmx_ch2_red
    green: dmx_ch2_green
    blue: dmx_ch2_blue

  - platform: rgb
    name: "Growlight 11 - Light 39"
    internal: true
    id: dmx_light_addr15
    gamma_correct: 1.0
    default_transition_length: 0s
    red: dmx_ch3_red
    green: dmx_ch3_green
    blue: dmx_ch3_blue

  - platform: rgb
    name: "Growlight 12 - Light 46"
    internal: true
    id: dmx_light_addr27
    gamma_correct: 1.0
    default_transition_length: 0s
    red: dmx_ch4_red
    green: dmx_ch4_green
    blue: dmx_ch4_blue

  - platform: partition
    name: "DMX Growlights"
    gamma_correct: 1.0
    segments:
      - single_light_id: dmxbar_bar_1
      - single_light_id: dmxbar_bar_2
      - single_light_id: dmxbar_bar_3
      - single_light_id: dmxbar_bar_4
      - single_light_id: dmxbar_bar_5
      - single_light_id: dmxbar_bar_6
      - single_light_id: dmxbar_bar_7
      - single_light_id: dmxbar_bar_8
      - single_light_id: dmx_light_addr1
      - single_light_id: dmx_light_addr8
      - single_light_id: dmx_light_addr15
      - single_light_id: dmx_light_addr27
    effects:
      - wled:
      - addressable_rainbow:
      - addressable_color_wipe:
      - addressable_scan:
      - addressable_twinkle:
     #- !include effects/ColorShimmerEffect.yaml
      - addressable_lambda:
          name: Scroll with Music
          update_interval: 0s
          lambda: |-
            ((MusicLeds*) id(music_leds))->ShowFrame(MODE_SCROLL, &it);
      - addressable_lambda:
          name: Energy with Music
          update_interval: 0s
          lambda: |-
            ((MusicLeds*) id(music_leds))->ShowFrame(MODE_ENERGY, &it);
      - addressable_lambda:
          name: Spectrum with Music
          update_interval: 0s
          lambda: |-
            ((MusicLeds*) id(music_leds))->ShowFrame(MODE_SPECTRUM, &it);


  - platform: binary
    id: status
    output: out_led

  - platform: monochromatic
    name: "Growlight 09 - Light 25 Mode"
    internal: true
    id: dmx_mode_light_addr1
    gamma_correct: 1.0
    default_transition_length: 0s
    output: dmx_ch1_mode

  - platform: monochromatic
    name: "Growlight 10 - Light 32 Mode"
    internal: true
    id: dmx_mode_light_addr8
    gamma_correct: 1.0
    default_transition_length: 0s
    output: dmx_ch2_mode

  - platform: monochromatic
    name: "Growlight 11 - Light 39 Mode"
    internal: true
    id: dmx_mode_light_addr15
    gamma_correct: 1.0
    default_transition_length: 0s
    output: dmx_ch3_mode

  - platform: monochromatic
    name: "Growlight 12 - Light 46 Mode"
    internal: true
    id: dmx_mode_light_addr27
    gamma_correct: 1.0
    default_transition_length: 0s
    output: dmx_ch4_mode

  - platform: fastled_clockless
    chipset: WS2811
    pin: GPIO12
    num_leds: 1
    rgb_order: BRG
    name: "Fake FastLED WS2811 Light"
    internal: true

custom_component:
  - lambda: |-
      auto my_music_leds = new MusicLeds(
        12,     /* num of pixels */
        0.0035, /* threshold */
        15,     /* ws pin */
        14      /* data piG */
      );
      App.register_component(my_music_leds);
      return {my_music_leds};
    components:
      - id: music_leds
