esphome:
  name: "h801_hallway"
  platform: ESP8266
  board: esp01_1m
  esp8266_restore_from_flash: yes

wifi:
  ssid: !secret wifi-east
  password: !secret wifi-pwd

  use_address: h801-growled.ak-online.be

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "H801 Hallway Fallback Hotspot"
    password: !secret fallback-password

mdns:
  disabled: true

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
#api:

mqtt:
  broker: mqtt.ak-online.be
  discovery: true
  topic_prefix: esphome/h801_hallway

ota:

web_server:
  port: 80

sensor:
  - platform: wifi_signal
    name: "WiFi Signal H801 Hallway"
    update_interval: 60s

status_led:
  pin:
    number: GPIO05
    #inverted: True

output:
  - platform: esp8266_pwm
    pin: 12
    frequency: 1000 Hz
    id: pwm_b
  - platform: esp8266_pwm
    pin: 13
    frequency: 1000 Hz
    id: pwm_g
  - platform: esp8266_pwm
    pin: 15
    frequency: 1000 Hz
    id: pwm_r
  - platform: esp8266_pwm
    pin: 14
    frequency: 1000 Hz
    id: pwm_w1
  - platform: esp8266_pwm
    pin: 04
    frequency: 1000 Hz
    id: pwm_w2
  - platform: gpio
    pin: 05
    id: red_led
  - platform: gpio
    pin: 01
    id: green_led

light:
  - platform: monochromatic
    name: "Hallway Shelf Strip 1"
    id: strip1
    internal: true
    output: pwm_r
    restore_mode: ALWAYS_OFF
  - platform: monochromatic
    name: "Hallway Shelf Strip 2"
    id: strip2
    internal: true
    output: pwm_g
    restore_mode: ALWAYS_OFF
  - platform: monochromatic
    name: "Hallway Shelf Strip 3"
    id: strip3
    internal: true
    output: pwm_b
    restore_mode: ALWAYS_OFF
  - platform: monochromatic
    name: "Hallway Shelf Strip 4"
    id: strip4
    internal: true
    output: pwm_w2
    restore_mode: ALWAYS_OFF

  - platform: partition
    name: "Hallway Shelf"
    default_transition_length: 2s
    #gamma_correct: 1.0
    segments:
      - single_light_id: strip1
      - single_light_id: strip2
      - single_light_id: strip3
      - single_light_id: strip4
    effects:
      - addressable_rainbow:
      - addressable_color_wipe:
      - addressable_scan:
      - addressable_twinkle:
     #- !include effects/ColorShimmerEffect.yaml

  - platform: monochromatic
    name: "Hallway Shelf Toplight"
    output: pwm_w1
