esphome:
  name: h801_growled
  platform: ESP8266
  board: esp01_1m
  esp8266_restore_from_flash: yes

wifi:
  ssid: !secret wifi-east
  password: !secret wifi-pwd

  use_address: h801-growled.ak-online.be

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "H801 GrowLED Fallback Hotspot"
    password: "h4GKBUNL9pAE"

mdns:
  disabled: true

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
#api:

mqtt:
  broker: mqtt.ak-online.be
  discovery: true
  topic_prefix: esphome/h801_growled

ota:

web_server:
  port: 80

sensor:
  - platform: wifi_signal
    name: "WiFi Signal H801 Growlight"
    update_interval: 60s

status_led:
  pin:
    number: GPIO05
    #inverted: True

output:
  - platform: esp8266_pwm
    pin: 12
    frequency: 1000 Hz
    id: pwm_b
  - platform: esp8266_pwm
    pin: 13
    frequency: 1000 Hz
    id: pwm_g
  - platform: esp8266_pwm
    pin: 15
    frequency: 1000 Hz
    id: pwm_r
  - platform: esp8266_pwm
    pin: 14
    frequency: 1000 Hz
    id: pwm_w1
  - platform: esp8266_pwm
    pin: 04
    frequency: 1000 Hz
    id: pwm_w2
  - platform: gpio
    pin: 05
    id: red_led
  - platform: gpio
    pin: 01
    id: green_led

#remote_transmitter:
#  id: IRTX
#  pin: GPIO12
#  carrier_duty_percent: 50

light:
  - platform: monochromatic
    name: "Growled"
    output: pwm_r
  - platform: monochromatic
    name: "Mini-Herrnhuter"
    output: pwm_g
    effects:
      - flicker:
#  - platform: monochromatic
#    name: "B"
#    output: pwm_b
#  - platform: monochromatic
#    name: "downlight"
#    output: pwm_w1
#  - platform: monochromatic
#    name: "shelf-bottom"
#    output: pwm_w2

#switch:
#  - platform: template
#    name: tvon
#    turn_on_action:
#      - remote_transmitter.transmit_samsung:
#          data: 0xE0E040BF
