esphome:
  name: h801-alpha
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret wifi-east
  password: !secret wifi-pwd

  use_address: h801-alpha.ak-online.be

mdns:
  disabled: true

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
#api:

mqtt:
  broker: mqtt.ak-online.be
  discovery: true
  topic_prefix: esphome/h801_alpha

ota:

web_server:
  port: 80
  include_internal: true

button:
  - platform: restart
    name: "Restart"

sensor:
  - platform: wifi_signal
    name: "WiFi Signal H801 Alpha"
    update_interval: 60s

status_led:
  pin:
    number: GPIO05
    #inverted: True

output:
  - platform: esp8266_pwm
    pin: 12
    frequency: 1000 Hz
    id: pwm_b
  - platform: esp8266_pwm
    pin: 13
    frequency: 1000 Hz
    id: pwm_r
  - platform: esp8266_pwm
    pin: 15
    frequency: 1000 Hz
    id: pwm_g
  - platform: esp8266_pwm
    pin: 14
    frequency: 1000 Hz
    id: pwm_w1
  - platform: esp8266_pwm
    pin: 04
    frequency: 1000 Hz
    id: pwm_w2
  - platform: gpio
    pin: 01
    id: green_led

light:
  - platform: rgb
    name: "Bedroom Moodlight"
    red: pwm_g
    green: pwm_r
    blue: pwm_b
    gamma_correct: 1.0
    restore_mode: ALWAYS_OFF
#  - platform: monochromatic
#    name: "downlight"
#    output: pwm_w1
#  - platform: monochromatic
#    name: "shelf-bottom"
#    output: pwm_w2
