esphome:
  name: h801_beta
  platform: ESP8266
  board: esp01_1m
  esp8266_restore_from_flash: yes

wifi:
  ssid: !secret wifi-ssid
  password: !secret wifi-pwd

  use_address: h801-beta.ak-online.be

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "H801 Beta Fallback Hotspot"
    password: "h4GKBUNL9pAE"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
#api:

mqtt:
  broker: mqtt.ak-online.be
  discovery: true
  topic_prefix: esphome/h801_beta

ota:

web_server:
  port: 80

sensor:
  - platform: wifi_signal
    name: "WiFi Signal H801 Beta"
    update_interval: 60s

status_led:
  pin:
    number: GPIO05
    #inverted: True

output:
  - platform: esp8266_pwm
    pin: 12
    frequency: 1000 Hz
    id: pwm_b
  - platform: esp8266_pwm
    pin: 13
    frequency: 1000 Hz
    id: pwm_r
  - platform: esp8266_pwm
    pin: 15
    frequency: 1000 Hz
    id: pwm_g
  - platform: esp8266_pwm
    pin: 14
    frequency: 1000 Hz
    id: pwm_w1
  - platform: esp8266_pwm
    pin: 04
    frequency: 1000 Hz
    id: pwm_w2
  - platform: gpio
    pin: 05
    id: red_led
  - platform: gpio
    pin: 01
    id: green_led

light:
  - platform: monochromatic
    name: "Office Background"
    output: pwm_r
    gamma_correct: 1.0
  - platform: monochromatic
    name: "Office Workbench"
    output: pwm_g
    gamma_correct: 1.0
  - platform: monochromatic
    name: "Office BigLED"
    output: pwm_w1
    gamma_correct: 1.0
  - platform: monochromatic
    name: "Office Workbench Floor"
    output: pwm_w2
    gamma_correct: 1.0
