esphome:
  name: irmote
  platform: ESP8266
  board: esp12e
  #platformio_options:
  #upload_speed: 115200


wifi:
  ssid: !secret wifi-ssid
  password: !secret wifi-pwd

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "IR-Remote Fallback Hotspot"
    password: "h4GKBUNL9pAE"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
#api:

mqtt:
  broker: mqtt.ak-online.be
  discovery: true
  topic_prefix: esphome/irmote

ota:

web_server:
  port: 80

remote_receiver:
  id: IRRX
  pin: 
    number: GPIO04
    inverted: True
  dump: all

remote_transmitter:
  id: IRTX
  pin: GPIO05
  carrier_duty_percent: 100

climate:
    - platform: tcl112
      name: "Delonghi AC"
      receiver_id: IRRX
      transmitter_id: IRTX

switch:
  - platform: template
    name: TestTrigger
    turn_on_action:
      remote_transmitter.transmit_panasonic:
        address: 0x4004
        command: 0x100BCBD
  - platform: template
    name: tvon
    turn_on_action:
      - light.turn_on: status
      - remote_transmitter.transmit_samsung:
          data: 0xE0E040BF
      - delay: 0.2s
      - light.turn_off: status

output:
  - platform: gpio
    pin: GPIO02
    id: out_led
    inverted: true

light:
  - platform: binary
    id: status
    name: "Status LED"
    output: out_led
