esphome:
  name: irmote
  platform: ESP8266
  board: esp12e
  #platformio_options:
  #upload_speed: 115200


wifi:
  ssid: !secret wifi-ssid
  password: !secret wifi-pwd

  use_address: irmote.ak-online.be

mdns:
  disabled: true

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
#api:

mqtt:
  broker: mqtt.ak-online.be
  discovery: true
  topic_prefix: esphome/irmote

ota:

web_server:
  port: 80
  include_internal: true

button:
  - platform: restart
    name: restart

sensor:
    - platform: wifi_signal
      name: "WiFi Signal ESP IRmote"
      update_interval: 60s

remote_receiver:
  id: IRRX
  pin:
    number: GPIO04
    inverted: True
  dump: all

remote_transmitter:
  id: IRTX
  pin: GPIO05
  carrier_duty_percent: 50

switch:
  - platform: template
    name: Test-ClimateState
    turn_on_action:
      - remote_transmitter.transmit_nec:
          address: 0x1218
          command: 0x2110
    turn_off_action:
      - remote_transmitter.transmit_nec:
          address: 0x1218
          command: 0x80B0
  - platform: template
    name: TestTrigger
    turn_on_action:
      - remote_transmitter.transmit_panasonic:
          address: 0x4004
          command: 0x100BCBD
  - platform: template
    name: Test-tvon
    turn_on_action:
      - light.turn_on: status
      - remote_transmitter.transmit_samsung:
          data: 0xE0E040BF
      - delay: 0.2s
      - light.turn_off: status

output:
  - platform: gpio
    pin: GPIO02
    id: out_led
    inverted: true

light:
  - platform: binary
    id: status
    #name: "Status LED"
    output: out_led

climate:
  - platform: delonghi
    name: "Office AC (Test)"
    transmitter_id: IRTX
    receiver_id: IRRX
    supports_cool : true
    supports_heat : false
    visual:
      min_temperature: 16
      max_temperature: 32
      temperature_step: 1
