esphome:
  name: kitchen
  platform: ESP8266
  board: esp12e

wifi:
  ssid: !secret wifi-ssid
  password: !secret wifi-pwd

  use_address: esp-kitchen.ak-online.be

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Kitchen Fallback Hotspot"
    password: "h4GKBUNL9pAE"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
#api:

mqtt:
  broker: mqtt.ak-online.be
  discovery: true
  topic_prefix: esphome/kitchen

  on_message:
    topic: esphome/kitchen/light/kitchen_light/command/brightness
    qos: 0
    then:
      - logger.log:
          format: "incoming mqtt: %s, sent on as %f"
          args:
            - 'x.c_str()'
            - 'atof(x.c_str()) / 255.f'
      - light.control:
          id: "kitchen_light"
          brightness: !lambda return atof(x.c_str()) / 255.f;
          state: on
      - light.control:
          id: "back_light"
          brightness: !lambda return clamp( atof(x.c_str()) / 255.f * 1.2f, 0.0f, 1.0f);
          state: on
      - light.control:
          id: "front_light"
          brightness: !lambda return clamp((atof(x.c_str()) / 255.f - 0.5f)*2, 0.0f, 1.0f);
          state: on

ota:

web_server:
  port: 80

i2c:
  sda: GPIO4
  scl: GPIO5
  scan: True

sensor:
  - platform: wifi_signal
    name: "WiFi Signal ESP Kitchen"
    update_interval: 60s
  - platform: bme280
    temperature:
      name: "BME280 Temperature"
      oversampling: 16x
    pressure:
      name: "BME280 Pressure"
    humidity:
      name: "BME280 Humidity"
    address: 0x76
    update_interval: 30s


light:
  - platform: monochromatic
    name: "Kitchen Light"
    id: "kitchen_light"
    default_transition_length: 0.0s
    output: fake_out
    gamma_correct: 1.0
  - platform: monochromatic
    id: "back_light"
    default_transition_length: 0.0s
    output: out_back
    gamma_correct: 1.0
  - platform: monochromatic
    id: "front_light"
    default_transition_length: 0.0s
    output: out_front
    gamma_correct: 1.0


output:
  - platform: esp8266_pwm
    id: fake_out
    pin: GPIO15
  - platform: esp8266_pwm
    id: out_front
    pin: GPIO12
    frequency: 250 Hz
  - platform: esp8266_pwm
    id: out_back
    pin: GPIO14
    frequency: 250 Hz

