esphome:
  name: nsp-kitchen

esp32:
  board: esp32dev

wifi:
  ssid: !secret wifi-east
  password: !secret wifi-pwd

  use_address: nsp-kitchen.ak-online.be

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "NSPanel Kitchen Fallback Hotspot"
    password: !secret fallback-password

mdns:
  disabled: true

time:
  - platform: sntp
    id: sntp_time
    servers:
      - 172.16.0.1

api:

mqtt:
  broker: mqtt.ak-online.be
  discovery: true
  topic_prefix: esphome/nsp-kitchen

logger:

ota:

web_server:
  port: 80

uart:
  tx_pin: 16
  rx_pin: 17
  baud_rate: 115200

external_components:
  - source: github://pr#2956
    components: ["nextion"]

display:
  - platform: nextion
    id: disp
    update_interval: 250ms
    tft_url:  http://172.16.0.253/kitchen.tft
    lambda: |-
      static int first_run = 1;

      auto time = id(sntp_time).now();

      // don't do our first run, if the time is not valid yet
      if( ! time.is_valid() ) return;

      // update when starting and when it's midnight
      if( first_run || time.hour == 0 && time.minute == 0 && time.second == 0) {
        it.set_component_value("day", time.day_of_month);
        it.set_component_text("weekday", time.strftime("%a").c_str());
      }

      // update only once on the first minute of an hour
      if( first_run || time.minute == 0 && time.second == 0 ) it.set_component_value("hour", time.hour);

      // update only once every 15sec
      if( first_run || time.second % 15 == 0 ) it.set_component_value("minute", time.minute);

      // update each interval
      it.set_component_value("second", time.second);

      // update once a minute
      if( first_run || time.second == 0 ) it.set_component_value("temperature", id(temperature).state);

      // disable the forced update only needed on first run
      first_run = 0;

script:
  - id: flip_the_breaker
    then:
      - switch.turn_off: relay_1
      - delay: 2s
      - switch.turn_on: relay_1


binary_sensor:
  - platform: gpio
    id: left_button
    pin:
      number: 14
      inverted: true
    on_click:
      - if:
          condition:
              mqtt.connected:
          then:
            - binary_sensor.template.publish:
                id: mainlight_switch
                state: ON
          else:
            - logger.log: "no MQTT, performing relay powercycle"
            - script.execute: flip_the_breaker
    on_double_click:
      - script.execute: flip_the_breaker

  - platform: gpio
    id: right_button
    pin:
      number: 27
      inverted: true
    on_click:
      - binary_sensor.template.publish:
          id: counter_switch
          state: ON

  - platform: template
    name: Kitchen Main Light Switch
    id: mainlight_switch
    entity_category: config
    lambda: |-
      return false;

  - platform: template
    name: Kitchen Counter Light Switch
    id: counter_switch
    entity_category: config
    lambda: |-
      return false;

output:
  - platform: ledc
    id: buzzer_out
    pin:
      number: 21

switch:
  - platform: gpio
    name: Relay 1
    id: relay_1
    pin:
      number: 22
    restore_mode: ALWAYS_ON
    entity_category: config

  - platform: gpio
    name: Relay 2
    id: relay_2
    pin:
      number: 19
    restore_mode: ALWAYS_ON
    entity_category: config

  - platform: gpio
    name: Kitchen Panel Screen Power
    id: screen_power
    entity_category: config
    pin:
      number: 4
      inverted: true
    restore_mode: ALWAYS_ON

  - platform: template
    name: Kitchen Panel Upload TFT file
    entity_category: config
    lambda: "return false;"
    turn_on_action:
      - lambda: 'id(disp)->upload_tft();'

rtttl:
  id: buzzer
  output: buzzer_out


sensor:
  - platform: adc
    id: ntc_source
    pin: 38
    update_interval: 10s
    attenuation: 11db

  - platform: resistance
    id: resistance_sensor
    sensor: ntc_source
    configuration: DOWNSTREAM
    resistor: 11.2kOhm

  - platform: ntc
    id: temperature
    sensor: resistance_sensor
    calibration:
      b_constant: 3950
      reference_temperature: 25°C
      reference_resistance: 10kOhm
    name: "Kitchen Panel Temperature"
