esphome:
  name: rgb_mainframe
  platform: ESP32
  board: nodemcu-32s
  #platformio_options:
  #upload_speed: 115200

  on_boot:
    priority: -120
    then:
      - light.turn_on:
          id: strip
          brightness: 100%
          red: 100%
          green: 0%
          blue: 100%
          effect: "WLED"


wifi:
  ssid: !secret wifi-east
  password: !secret wifi-pwd

  use_address: rgb-mainframe.ak-online.be
  enable_mdns: false

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "RGB Mainframe Fallback Hotspot"
    password: !secret fallback-password

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
#api:

mqtt:
  broker: mqtt.ak-online.be
  discovery: true
  topic_prefix: esphome/rgb-mainframe

ota:

web_server:
  port: 80
  include_internal: true

#esp32_ble_beacon:
#  type: iBeacon
#  uuid: 'f4feef4e-ca5e-82f4-7e7d-cc3c08fa162f'

wled:

sensor:
  - platform: wifi_signal
    name: "WiFi Signal RGB Mainframe"
    update_interval: 60s

output:
  - platform: gpio
    pin: GPIO02
    id: out_led

  - platform: ledc
    id: out_fet1
    pin: GPIO16
    frequency: 25000 Hz

    # driven to gnd via mosfet, hence
    inverted: true

light:
  - platform: binary
    id: status
    output: out_led

  - platform: fastled_clockless
    id: strip
    chipset: WS2812B
    pin: GPIO17
    # this should be increased once fan is in the chain
    #num_leds: 30
    num_leds: 32
    rgb_order: GRB
    effects:
      - wled:
      - !include effects/ColorShimmerEffect.yaml
