esphome:
  name: rgbcontroller_prototype
  platform: ESP8266
  board: nodemcuv2
  #platformio_options:
  #upload_speed: 115200


wifi:
  ssid: !secret wifi-ssid
  password: !secret wifi-pwd

  use_address: rgbcontroller_prototype.ak-online.be

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "RGB Controller Fallback Hotspot"
    password: "h4GKBUNL9pAE"

captive_portal:

# Enable logging
logger:
  #level: VERY_VERBOSE
  #logs:
  #  fastled: DEBUG
  #  sensor: DEBUG

# Enable Home Assistant API
#api:

mqtt:
  broker: mqtt.ak-online.be
  discovery: true
  topic_prefix: esphome/rgbcontroller_prototype

ota:

wled:

e131:
  method: multicast

web_server:
  port: 80

sensor:
  - platform: wifi_signal
    name: "WiFi Signal rgbcontroller_prototype"
    update_interval: 60s

output:
  - platform: gpio
    pin: GPIO04
    id: out_led
    inverted: true

light:
  - platform: binary
    id: status
    output: out_led

  - platform: fastled_spi
    id: strip
    name: strip
    chipset: APA102
    data_pin: D6
    clock_pin: D5
    num_leds: 30
    rgb_order: BGR
    effects:
      - !include ColorShimmerEffect.yaml
#     - addressable_lambda:
#          name: "Test Dump"
#          update_interval: 20s
#          lambda: |-
#            for( int i = 0; i < it.size(); i++ ){
#              ESPColor c = it[i].get();
#              ESP_LOGD("strip-dump", "led %d is %d,%d,%d", i, c.r, c.g, c.b );
#            }

  - platform: partition
    name: "Input Interface"
    id: input
    segments:
      - id: strip
        from: 0
        to: 23
    effects:
      - wled:
      - e131:
          universe: 2
          channels: RGB
