esphome:
  name: ssr
  platform: ESP8266
  board: esp12e
  esp8266_restore_from_flash: yes

wifi:
  ssid: !secret wifi-ssid
  password: !secret wifi-pwd

#  use_address: esp-balkony.ak-online.be

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "SSR Fallback Hotspot"
    password: "h4GKBUNL9pAE"

mdns:
  disabled: true

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
#api:

mqtt:
  broker: mqtt.ak-online.be
  discovery: true
  topic_prefix: esphome/ssr

ota:

web_server:
  port: 80

sensor:
  - platform: wifi_signal
    name: "WiFi Signal ESP SSR"
    update_interval: 60s

light:
  - platform: binary
    name: Herrnhuter
    id: herrnhuter
    output: ssr
    on_turn_on:
      - light.turn_on:
          id: status
    on_turn_off:
      - light.turn_off:
          id: status

  - platform: binary
    id: status
    output: out_led

script:
  - id: runON
    then:
      - light.turn_on:
          id: herrnhuter
  - id: runOFF
    then:
      - light.turn_off:
          id: herrnhuter
          transition_length: 0ms
  - id: run_toggles
    then:
      # turn on to start from the ON state
      - script.execute: runON
      - script.wait: runON
      - delay: 10s

      # start the reset sequence
      - script.execute: runOFF
      - script.wait: runOFF
      - delay: 1s
      - script.execute: runON
      - script.wait: runON
      - delay: 1s

      - script.execute: runOFF
      - script.wait: runOFF
      - delay: 1s
      - script.execute: runON
      - script.wait: runON
      - delay: 1s

      - script.execute: runOFF
      - script.wait: runOFF
      - delay: 1s
      - script.execute: runON
      - script.wait: runON
      - delay: 1s

      - script.execute: runOFF
      - script.wait: runOFF
      - delay: 1s
      - script.execute: runON
      - script.wait: runON
      - delay: 1s

      - script.execute: runOFF
      - script.wait: runOFF
      - delay: 1s
      - script.execute: runON
      - script.wait: runON

switch:
  - platform: template
    name: run zigbee light reset
    turn_on_action:
      - script.execute: run_toggles

output:
  - platform: gpio
    pin: GPIO02
    id: out_led
    inverted: true

  - platform: gpio
    id: ssr
    pin: GPIO13
