esphome:
  name: tester
  platform: ESP8266
  board: esp12e
  platformio_options:
    upload_speed: 115200


wifi:
  ssid: !secret wifi-ssid
  password: !secret wifi-pwd

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Tester Fallback Hotspot"
    password: "h4GKBUNL9pAE"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
#api:

mqtt:
  broker: mqtt.ak-online.be
  discovery: true
  topic_prefix: esphome/tester

ota:

web_server:
  port: 80

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
    name: "Tester Button"
    filters:
      - delayed_on_off: 50ms
