esphome:
  name: tuya3
  platform: ESP8266
  board: esp_wroom_02


wifi:
  ssid: !secret wifi-east
  password: !secret wifi-pwd

  use_address: tuya3.ak-online.be

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Tuya3 Fallback Hotspot"
    password: "h4GKBUNL9pAE"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
#api:

mqtt:
  broker: mqtt.ak-online.be
  discovery: true

  topic_prefix: esphome/tuya3

  on_message:
    topic: shellies/shellyswitch-9F5EF6/relay/power
    qos: 0
    then:
      - logger.log:
          format: "incoming mqtt: %s, sent on as %s"
          args:
            - 'x.c_str()'
            - 'atof(x.c_str()) > 10 ? "on" : "off"'
      - light.control:
          id: "some_led_light"
          state: !lambda 'return atof(x.c_str()) > 10 ;'

ota:

web_server:
  port: 80

sensor:
  - platform: wifi_signal
    name: "WiFi Signal tuya3"
    update_interval: 60s
  - platform: mqtt_subscribe
    id: "rollerpower"
    topic: shellies/shellyswitch-9F5EF6/relay/power

output:
  - platform: esp8266_pwm
    id: yellow_led
    pin: GPIO00

  - platform: esp8266_pwm
    id: some_led
    pin: GPIO15

light:
  - platform: binary
    id: yellow_led_light
    #    name: "Yellow LED"
    output: yellow_led
  - platform: binary
    id: some_led_light
    #name: "some LED"
    output: some_led

binary_sensor:
  - platform: gpio
    name: "open"
    pin:
      number: GPIO05
      inverted: True
    on_press:
      then:
        - light.turn_on: yellow_led_light
    on_release:
      then:
        - light.turn_off: yellow_led_light

  - platform: template
    name: "stop"
    id: "stop"
    lambda: |-
      return false;
  - platform: template
    name: "videoled-button"
    id: "videoled_button"
    lambda: |-
      return false;
  - platform: template
    name: "underdesk-button"
    id: "underdesk_button"
    lambda: |-
      return false;

  - platform: gpio
    id: "stopbutton"
    pin:
      number: GPIO03
      inverted: True
    on_press:
      then:
        - light.turn_on: yellow_led_light
    on_release:
      then:
        - light.turn_off: yellow_led_light
    on_click:
      - min_length: 50ms
        max_length: 500ms
        then:
        - if:
            condition:
              lambda: 'return id(rollerpower).state > 10;'
            then:
              - binary_sensor.template.publish:
                  id: "stop"
                  state: ON
            else:
              - binary_sensor.template.publish:
                  id: "videoled_button"
                  state: ON

      - min_length: 500ms
        max_length: 2000ms
        then:
        - binary_sensor.template.publish:
            id: "underdesk_button"
            state: ON

  - platform: gpio
    name: "close"
    pin:
      number: GPIO12
      inverted: True
    on_press:
      then:
        - light.turn_on: yellow_led_light
    on_release:
      then:
        - light.turn_off: yellow_led_light
