esphome:
  name: tuya3
  platform: ESP8266
  board: esp_wroom_02
  includes:
    - holtek.h


wifi:
  ssid: !secret wifi-ssid
  password: !secret wifi-pwd

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Tuya3 Fallback Hotspot"
    password: "h4GKBUNL9pAE"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
#api:

mqtt:
  broker: mqtt.ak-online.be
  discovery: true

ota:

web_server:
  port: 80

output:
  - platform: esp8266_pwm
    id: yellow_led
    pin: GPIO00

light:
  - platform: binary
    name: "Yellow LED"
    output: yellow_led

i2c:
    sda: GPIO05
    scl: GPIO03
    scan: True

binary_sensor:
  #  - platform: gpio
  #  pin:
  #    number: GPIO0
  #    mode: INPUT_PULLUP
  #    inverted: True
  #  name: "Touchpad 1"
  #- platform: gpio
  #  pin:
  #    number: GPIO9
  #    mode: INPUT_PULLUP
  #    inverted: True
  #  name: "Touchpad 2"
  #- platform: gpio
  #  pin:
  #    number: GPIO10
  #    mode: INPUT_PULLUP
  #    inverted: True
  #  name: "Touchpad 3"
  #- platform: status
  #  name: "Status"

custom_component:
  - id: htc
    lambda: |-
      auto my_custom_sensor = new HoltekChip();
      App.register_component(my_custom_sensor);
      return {my_custom_sensor};
