esphome:
  name: tuya3
  platform: ESP8266
  board: esp_wroom_02


wifi:
  ssid: !secret wifi-ssid
  password: !secret wifi-pwd

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Tuya3 Fallback Hotspot"
    password: "h4GKBUNL9pAE"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
#api:

mqtt:
  broker: mqtt.ak-online.be
  discovery: true

ota:

web_server:
  port: 80

output:
  - platform: esp8266_pwm
    id: yellow_led
    pin: GPIO00

light:
  - platform: binary
    id: yellow_led_light
    name: "Yellow LED"
    output: yellow_led

binary_sensor:
  - platform: gpio
    name: "open"
    pin:
      number: GPIO05
      inverted: True
    on_press:
      then:
        - light.turn_on: yellow_led_light
    on_release:
      then:
        - light.turn_off: yellow_led_light
  - platform: gpio
    name: "stop"
    pin:
      number: GPIO03
      inverted: True
    on_press:
      then:
        - light.turn_on: yellow_led_light
    on_release:
      then:
        - light.turn_off: yellow_led_light
  - platform: gpio
    name: "close"
    pin:
      number: GPIO12
      inverted: True
    on_press:
      then:
        - light.turn_on: yellow_led_light
    on_release:
      then:
        - light.turn_off: yellow_led_light
