esphome:
  name: videoled
  platform: ESP8266
  board: esp12e
  #platformio_options:
  #upload_speed: 115200
  esp8266_restore_from_flash: yes


wifi:
  ssid: !secret wifi-east
  password: !secret wifi-pwd

  use_address: videoled.ak-online.be

mdns:
  disabled: true

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
#api:

mqtt:
  broker: mqtt.ak-online.be
  discovery: true
  topic_prefix: esphome/videoled

ota:

web_server:
  port: 80
  include_internal: true

sensor:
  - platform: wifi_signal
    name: "WiFi Signal VideoLED"
    update_interval: 60s

output:
  - platform: gpio
    pin: GPIO02
    id: out_led
    inverted: true

  - platform: esp8266_pwm
    id: out_fet1
    pin: GPIO12
    frequency: 1000 Hz

  - platform: esp8266_pwm
    id: out_fet2
    pin: GPIO13
    frequency: 1000 Hz

light:
  - platform: binary
    id: status
    internal: true
    output: out_led
    entity_category: diagnostic

  - platform: monochromatic
    name: "Video LED"
    id: "videoled"
    default_transition_length: 0.5s
    output: out_fet1

  - platform: monochromatic
    name: "UnderDesk LED"
    id: "underdesk"
    default_transition_length: 0.5s
    output: out_fet2
