esphome:
  name: videoled
  platform: ESP8266
  board: esp12e
  #platformio_options:
  #upload_speed: 115200


wifi:
  ssid: !secret wifi-ssid
  password: !secret wifi-pwd

  use_address: videoled.ak-online.be

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "VideoLED Fallback Hotspot"
    password: "h4GKBUNL9pAE"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
#api:

mqtt:
  broker: mqtt.ak-online.be
  discovery: true
  topic_prefix: esphome/videoled

ota:

web_server:
  port: 80

sensor:
  - platform: wifi_signal
    name: "WiFi Signal VideoLED"
    update_interval: 60s

output:
  - platform: gpio
    pin: GPIO02
    id: out_led
    inverted: true

  - platform: esp8266_pwm
    id: out_fet1
    pin: GPIO12
    frequency: 1000 Hz

light:
  - platform: binary
    id: status
    name: "Status LED"
    output: out_led

  - platform: monochromatic
    name: "Video LED"
    id: "videoled"
    default_transition_length: 0.5s
    output: out_fet1

remote_transmitter:
  id: IRTX
  pin: GPIO12
  carrier_duty_percent: 50

switch:
  - platform: template
    name: tvon
    turn_on_action:
      - remote_transmitter.transmit_samsung:
          data: 0xE0E040BF
  - platform: template
    name: ClimateState
    turn_on_action:
      remote_transmitter.transmit_nec:
        address: 0x1218
        command: 0x2110
    turn_off_action:
      remote_transmitter.transmit_nec:
        address: 0x1218
        command: 0x80B0

binary_sensor:
  - platform: gpio
    #name: "gpio0"
    id: gpio0
    pin:
      number: GPIO00
    on_press:
      then:
        - light.turn_on: status
    on_release:
      then:
        - light.turn_off: status
