esphome:
  name: videoled
  platform: ESP8266
  board: esp12e
  #platformio_options:
  #upload_speed: 115200


wifi:
  ssid: !secret wifi-ssid
  password: !secret wifi-pwd

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "VideoLED Fallback Hotspot"
    password: "h4GKBUNL9pAE"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
#api:

mqtt:
  broker: mqtt.ak-online.be
  discovery: true
  topic_prefix: esphome/videoled

ota:

web_server:
  port: 80

output:
  - platform: gpio
    pin: GPIO02
    id: out_led
    inverted: true

  - platform: esp8266_pwm
    id: out_fet1
    pin: GPIO12
    frequency: 1000 Hz

light:
  - platform: binary
    id: status
    name: "Status LED"
    output: out_led

  - platform: monochromatic
    name: "Video LED"
    id: "videoled"
    default_transition_length: 0.5s
    output: out_fet1

binary_sensor:
  - platform: gpio
    name: "gpio0"
    pin:
      number: GPIO00
    on_press:
      then:
        - light.turn_on: status
    on_release:
      then:
        - light.turn_off: status
